"""add_weight_kg_to_item

Revision ID: 7a4ff96e148b
Revises: b403e4156aa4
Create Date: 2026-06-09 22:29:05.220431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4ff96e148b'
down_revision: Union[str, Sequence[str], None] = 'b403e4156aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('weight_kg', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'weight_kg')
    # ### end Alembic commands ###
