"""add_checkout_and_settings

Revision ID: 7b84038b99ac
Revises: 7a4ff96e148b
Create Date: 2026-07-14 20:12:17.188899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b84038b99ac'
down_revision: Union[str, Sequence[str], None] = '7a4ff96e148b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.add_column('cart_items', sa.Column('is_selected', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('order_items', sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('order_items', sa.Column('line_total', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('invoice_no', sa.String(length=30), server_default='DEFAULT-INV', nullable=False))
    op.add_column('orders', sa.Column('order_type', sa.Enum('DELIVERY', 'PICKUP', name='ordertype', native_enum=False), server_default='DELIVERY', nullable=False))
    op.add_column('orders', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.alter_column('orders', 'delivery_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('orders', 'payment_method',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Enum('COD', 'WHATSAPP', name='paymentmethod', native_enum=False),
               existing_nullable=False)
    op.alter_column('orders', 'delivery_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_orders_invoice_no'), 'orders', ['invoice_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_invoice_no'), table_name='orders')
    op.alter_column('orders', 'delivery_address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'payment_method',
               existing_type=sa.Enum('COD', 'WHATSAPP', name='paymentmethod', native_enum=False),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    op.alter_column('orders', 'delivery_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_column('orders', 'tax_amount')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'order_type')
    op.drop_column('orders', 'invoice_no')
    op.drop_column('order_items', 'line_total')
    op.drop_column('order_items', 'discount_price')
    op.drop_column('cart_items', 'is_selected')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
