"""add unique constraint to item name

Revision ID: cbc45c1bd022
Revises: e521352b390e
Create Date: 2026-05-12 08:37:45.851923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc45c1bd022'
down_revision: Union[str, Sequence[str], None] = 'e521352b390e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_item_name', 'items', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_item_name', 'items', type_='unique')
    # ### end Alembic commands ###
